title: Aipnur — Personal Website
description: Portfolio of Aipnur | Digital designer & developer | Web design, UI/UX, and modern web development projects
url: "https://aipnur.id"
baseurl: ""

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num/"
permalink: /:year/:month/:day/:slug.html
